version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    restart: always
    environment:
      TGBOT_TOKEN: "${TGBOT_TOKEN}"
      DB_PWD: "${DB_PWD}"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PWD}"

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: